python3 create_stream_rate.py --prefix dataspace/graph/yeast/yeast  --epochs 20 --pretrained_model  model_pt/yeast_sup_20.pt --save_model  model_pt/yeast_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new --rate 100
python3 create_stream_rate.py --prefix dataspace/graph/human/human  --epochs 20 --pretrained_model  model_pt/human_sup_20.pt --save_model  model_pt/human_sup_20.pt --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new  --rate 100
python3 create_stream_rate.py --prefix dataspace/graph/cora/cora  --epochs 20 --pretrained_model  model_pt/cora_sup_20.pt --save_model  model_pt/cora_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new  --rate 100
python3 create_stream_rate.py --prefix dataspace/graph/citeseer/citeseer  --epochs 20 --pretrained_model  model_pt/citeseer_sup_20.pt --save_model  model_pt/citeseer_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new  --rate 100
python3 create_stream_rate.py --prefix dataspace/graph/pubmed/pubmed  --epochs 20 --pretrained_model  model_pt/pubmed_sup_20.pt --save_model  model_pt/pubmed_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new  --rate 100
python3 create_stream_rate.py --prefix dataspace/graph/wordnet/wordnet  --epochs 20 --pretrained_model  model_pt/wordnet_sup_20.pt --save_model  model_pt/wordnet_sup_20.pt --cuda --num_subgraphs 20 --embedding_model ../data/rate_exp_new  --rate 100
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/yeast/yeast  --epochs 10 --pretrained_model  model_pt/yeast_sup_10.pt  --cuda --num_subgraphs 20 --embedding_model ../data
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/human/human  --epochs 10 --pretrained_model  model_pt/human_sup_10.pt --cuda --num_subgraphs 20 --embedding_model ../data 
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/cora/cora  --epochs 10 --pretrained_model  model_pt/cora_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data 
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/citeseer/citeseer  --epochs 10 --pretrained_model  model_pt/cs_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data 
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/pubmed/pubmed  --epochs 10 --pretrained_model  model_pt/pubmed_sup_20.pt  --cuda --num_subgraphs 20 --embedding_model ../data 
# python3 create_stream_coldstart_kmean.py --prefix dataspace/graph/wordnet/wordnet  --epochs 10 --pretrained_model  model_pt/wordnet-sup-3.pt --cuda --num_subgraphs 20 --embedding_model ../data 
